### ISSUE TITLE
panic: runtime error: index out of range 

### ISSUE THREAD

**Issue by link89** [PKUHPC/scow-slurm-adapter#20]
在使用过程中出现一次 panic, 日志上下文如下

```text
{"level":"info","msg":"Received request GetClusterConfig: ","time":"2024-09-12T15:26:12+08:00"}
{"level":"info","msg":"Received request GetClusterConfig: ","time":"2024-09-12T15:26:16+08:00"}
{"level":"info","msg":"Received request GetJobs: fields:\"job_id\" fields:\"partition\" fields:\"name\" fields:\"user\" fields:\"state\" fields:\"elapsed_seconds\" fields:\"nodes_alloc\" fields:\"node_list\" fields:\"reason\" fields:\"account\" fields:\"cpus_alloc\" fields:\"gpus_alloc\" fields:\"qos\" fields:\"submit_time\" fields:\"time_limit_minutes\" fields:\"working_directory\" filter:{users:\"whxu\" accounts:\"freshmen\" accounts:\"alumni\" accounts:\"comsol\" accounts:\"researcher\" accounts:\"root\" states:\"RUNNING\" states:\"PENDING\"}","time":"2024-09-12T15:26:27+08:00"}
{"level":"info","msg":"Received request GetClusterConfig: ","time":"2024-09-12T15:30:00+08:00"}
{"level":"info","msg":"Received request GetJobs: fields:\"job_id\" fields:\"name\" fields:\"user\" fields:\"account\" fields:\"cpus_alloc\" fields:\"gpus_alloc\" fields:\"mem_alloc_mb\" fields:\"mem_req_mb\" fields:\"partition\" fields:\"qos\" fields:\"elapsed_seconds\" fields:\"node_list\" fields:\"nodes_req\" fields:\"nodes_alloc\" fields:\"time_limit_minutes\" fields:\"submit_time\" fields:\"start_time\" fields:\"end_time\" filter:{end_time:{start_time:{seconds:1726125387} end_time:{seconds:1726126202 nanos:646000000}}} page_info:{page:1 page_size:1}","time":"2024-09-12T15:30:02+08:00"}
{"level":"info","msg":"Received request GetJobs: fields:\"job_id\" fields:\"name\" fields:\"user\" fields:\"account\" fields:\"cpus_alloc\" fields:\"gpus_alloc\" fields:\"mem_alloc_mb\" fields:\"mem_req_mb\" fields:\"partition\" fields:\"qos\" fields:\"elapsed_seconds\" fields:\"node_list\" fields:\"nodes_req\" fields:\"nodes_alloc\" fields:\"time_limit_minutes\" fields:\"submit_time\" fields:\"start_time\" fields:\"end_time\" filter:{end_time:{start_time:{seconds:1726125387} end_time:{seconds:1726126202 nanos:646000000}}}","time":"2024-09-12T15:30:02+08:00"}
{"level":"info","msg":"Received request GetClusterInfo: ","time":"2024-09-12T15:31:00+08:00"}
panic: runtime error: index out of range [4] with length 4

goroutine 33682 [running]:
scow-slurm-adapter/services/config.(*ServerConfig).GetClusterInfo(0x975480?, {0xc00060d2f0?, 0x4eff06?}, 0xc00051e270?)
        /data/home/whxu/src/scow-slurm-adapter/services/config/config.go:939 +0x1c09
scow-slurm-adapter/gen/go._ConfigService_GetClusterInfo_Handler({0x975840?, 0xe4e7b0}, {0xabf280, 0xc00060d2c0}, 0xc000121d80, 0x0)
        /data/home/whxu/src/scow-slurm-adapter/gen/go/config_grpc.pb.go:196 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e2200, {0xabf280, 0xc00060d200}, {0xac21d8, 0xc000149e00}, 0xc00019b0e0, 0xc0001ef380, 0xe11270, 0x0)
        /data/home/whxu/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1379 +0xe9b
google.golang.org/grpc.(*Server).handleStream(0xc0001e2200, {0xac21d8, 0xc000149e00}, 0xc00019b0e0)
        /data/home/whxu/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1790 +0xd8f
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /data/home/whxu/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1029 +0x91
created by google.golang.org/grpc.(*Server).serveStreams.func2
        /data/home/whxu/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1040 +0x145
```

版本：1.6.0
操作系统：CentOS 7.6
slurm 22.05.6

**Comment by link89** [comment]
进一步的观察发现，这一问题从作业界面切换到仪表盘界面时会100%复现，步骤可参考附件。


Uploading scow-slurm-adapter-panic.mp4…

**Comment by link89** [comment]
与此同时，scow服务有如下报错
```
mis-server-1     | {"level":30,"time":"2024-09-13T02:23:08.073Z","pid":19,"hostname":"98fd1a8e6509","req":"8y","path":"/scow.server.ConfigService/GetClustersRuntimeInfo","msg":"Starting request"}
mis-server-1     | {"level":30,"time":"2024-09-13T02:23:08.075Z","pid":19,"hostname":"98fd1a8e6509","req":"8y","path":"/scow.server.ConfigService/GetClustersRuntimeInfo","msg":"Current clusters list: Cluster ID: chenglab, Current Status: ACTIVATED"}
mis-server-1     | {"level":30,"time":"2024-09-13T02:23:08.075Z","pid":19,"hostname":"98fd1a8e6509","req":"8y","path":"/scow.server.ConfigService/GetClustersRuntimeInfo","msg":"Request completed."}
portal-server-1  | {"level":30,"time":"2024-09-13T02:23:08.077Z","pid":18,"hostname":"8a5ee9512306","msg":"Checking activation status of clusters with ids ([\"chenglab\"]) "}
portal-server-1  | {"level":30,"time":"2024-09-13T02:23:08.077Z","pid":18,"hostname":"8a5ee9512306","req":"2t","path":"/scow.portal.ConfigService/GetClusterNodesInfo","msg":"Calling actions on cluster chenglab"}
portal-server-1  | {"level":50,"time":"2024-09-13T02:23:08.078Z","pid":18,"hostname":"8a5ee9512306","req":"2t","path":"/scow.portal.ConfigService/GetClusterNodesInfo","msg":"Cluster ops fails at {\"code\":12,\"message\":\"unimplemented\",\"details\":\"The scheduler API version can not be confirmed.To use this method, the scheduler adapter must be upgraded to the version 1.6.0 or higher.\"}"}
portal-server-1  | {"level":50,"time":"2024-09-13T02:23:08.078Z","pid":18,"hostname":"8a5ee9512306","req":"2t","path":"/scow.portal.ConfigService/GetClusterNodesInfo","code":12,"message":"unimplemented","details":"The scheduler API version can not be confirmed.To use this method, the scheduler adapter must be upgraded to the version 1.6.0 or higher.","msg":"Error occurred. Return the error."}
portal-web-1     | Error: 12 UNIMPLEMENTED: The scheduler API version can not be confirmed.To use this m
```

**Comment by link89** [comment]
追加新问题
```
panic: runtime error: index out of range [1] with length 1

goroutine 2365 [running]:
scow-slurm-adapter/services/config.(*ServerConfig).GetClusterInfo(0x975480?, {0xc00024d410?, 0x4eff06?}, 0xc000a3b590?)
        /data/home/whxu/src/scow-slurm-adapter/services/config/config.go:946 +0x1c25
scow-slurm-adapter/gen/go._ConfigService_GetClusterInfo_Handler({0x975840?, 0xe4e7b0}, {0xabf280, 0xc00024d3e0}, 0xc0001b8400, 0x0)
        /data/home/whxu/src/scow-slurm-adapter/gen/go/config_grpc.pb.go:196 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002c6000, {0xabf280, 0xc00024d350}, {0xac21d8, 0xc0002f0000}, 0xc0003a0a20, 0xc000286360, 0xe11270, 0x0)
        /data/home/whxu/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1379 +0xe9b
google.golang.org/grpc.(*Server).handleStream(0xc0002c6000, {0xac21d8, 0xc0002f0000}, 0xc0003a0a20)
        /data/home/whxu/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1790 +0xd8f
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /data/home/whxu/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1029 +0x91
created by google.golang.org/grpc.(*Server).serveStreams.func2
        /data/home/whxu/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1040 +0x145
```

**Comment by link89** [comment]
根本原因是对以下类型的 sinfo 输出解析错误
```bash
sinfo -p gpu-all --noheader --format='%P %c %C %G %a %D %F'
gpu-all 64 10/54/0/64 gpu:a100:2,gpu:1g.10gb:14 up 1 1/0/0/1
gpu-all 32 1/127/0/128 gpu:2080ti:8 up 4 1/3/0/4
gpu-all 32 0/32/0/32 gpu:v100:4 up 1 0/1/0/1
```
